name: volunteers_yemen
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
        sdk: flutter
  get: ^4.6.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  flutter_gradient_button: ^0.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
   
  
flutter_intl:
  enabled: true
